hide-cursor-when-typing = true

theme = "catppuccin-macchiato"

line-height = 1.1
# env-vars = []
confirm-before-quit = false

[cursor]
shape = 'block'
blinking = true
blinking-interval = 800

[window]
opacity = 0.95
blur = true

[fonts]
family = "JetBrains Mono"
size = 22

[scroll]
multiplier = 5.0
divider = 1.0

[navigation]
hide-if-single = true
use-current-path = true
mode = "TopTab"

[shell]
program = "fish"

[bindings]
keys = [
  { key = "t", with = "control", action = "CreateTab" },
  { key = "1", with = "alt", action = "SelectTab(0)" },
  { key = "2", with = "alt", action = "SelectTab(1)" },
  { key = "3", with = "alt", action = "SelectTab(2)" },
  { key = "4", with = "alt", action = "SelectTab(3)" },
  { key = "5", with = "alt", action = "SelectTab(4)" },
  { key = "6", with = "alt", action = "SelectTab(5)" },
  { key = "7", with = "alt", action = "SelectTab(6)" },
  { key = "8", with = "alt", action = "SelectTab(7)" },
  { key = "9", with = "alt", action = "SelectTab(8)" },
  { key = "0", with = "alt", action = "SelectTab(9)" },
]
