[config]
version_check = false

[templates.zellij]
input_path = "~/.config/matugen/templates/zellij.kdl"
output_path = "~/.config/zellij/themes/matugen.kdl"
post_hook = "touch ~/.config/zellij/config.kdl"
