#!/usr/bin/env bash

[ -f ~/.config/river/multihead-setup.sh ] && ~/.config/river/multihead-setup.sh

riverctl keyboard-layout -variant altgr-intl us

riverctl map normal Super Return spawn wezterm
riverctl map normal Super B spawn firefox
riverctl map normal Super E spawn thunar
riverctl map normal Super R spawn 'tofi-drun --drun-launch=true'

riverctl map normal Super Q close

riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift F toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl map normal Super+Shift i send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift r send-layout-cmd rivertile "main-count 1"
riverctl map normal Super+Shift L spawn hyprlock

riverctl map normal None XF86AudioRaiseVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ +1%'
riverctl map normal None XF86AudioLowerVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ -1%'
riverctl map normal None XF86AudioMute spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

for i in $(seq 1 9); do
	tags=$((1 << ($i -1)))

	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal Super J focus-view next 
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl focus-follows-cursor normal

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.5 &

riverctl rule-add -app-id firefox ssd
riverctl rule-add -title Picture-in-Picture float
riverctl rule-add -title 'File Operation Progress' float
riverctl rule-add -app-id mpv float
riverctl rule-add -app-id oculante float
riverctl rule-add -app-id 'org.edgetx.companion*' float
riverctl rule-add -app-id 'com.usebottles.bottles' float
riverctl rule-add -app-id 'org.raspberrypi.rpi-imager' float
riverctl rule-add -app-id org.pulseaudio.pavucontrol float

riverctl border-width 3

swww-daemon &
yambar &
cycle-wallpapers.sh 600 &
