#!/bin/sh

riverctl map normal Super Return spawn kitty
riverctl map normal Super B spawn firefox

riverctl map normal Super Q close

riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift F toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9); do
	tags=$((1 << ($i -1)))

	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal Super J focus-view next 
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl focus-follows-cursor normal

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.5 &

riverctl rule-add -app-id firefox ssd

riverctl border-width 3
