bar:
  height: 32
  location: top
  background: 00000099
  foreground: DDDDDDFF
  font: JetBrainsMono:pixelsize=18
  left:
    - river:
        content:
          map:
            conditions:
              focused:
                string:
                  left-margin: 12
                  text: "{id}"
              occupied:
                string:
                  left-margin: 12
                  foreground: FFFFFF55
                  text: "{id}"
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "[{app-id}]", left-margin: 10, foreground: 999999ff}
                - string: {text: " {title}"}
  center:
    - clock:
        content:
          - string: {text: "{time}", right-margin: 10}

  right:
    - pipewire:
        content:
          map:
            default:
              string:
                right-margin: 15
                text: ""
            conditions:
              type == "sink" && muted:
                string:
                  text: "MUTED"
                  foreground: FF000077
              type == "sink":
                string:
                  text: "{linear_volume}%"
