bar:
  height: 32
  location: top
  background: 00000099
  foreground: DDDDDDFF
  font: JetBrainsMono:pixelsize=18:weight=bold
  left:
    - river:
        content:
          map:
            conditions:
              focused:
                string:
                  left-margin: 12
                  text: "{id}"
              occupied:
                string:
                  left-margin: 12
                  foreground: FFFFFF55
                  text: "{id}"
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "[{app-id}]", left-margin: 12, foreground: FFFFFF55}
                - string: {text: " {title}"}
  center:
    - clock:
        content:
          - string:
              text: "{time}"
              foreground: FFFFFF99

  right:
    - pipewire:
        content:
          map:
            on-click:
              left: pavucontrol
            default:
              string:
                right-margin: 12
                foreground: FFFFFF99
                text: ""
            conditions:
              type == "sink" && muted:
                string:
                  text: "muted"
              type == "sink":
                string:
                  text: "{linear_volume}%"
