directory: ~/Music
library: ~/Sync/beets.db
import:
  move: yes
  languages: fr en
plugins:
  - deezer
  - musicbrainz
  - the
  - embedart
  - fetchart
  - scrub
  - ftintitle
  - replaygain
  - zero
original_date: yes
# replace:
#   "Alt236": "ALT 236"
#   "&": "and"
#   '[*<>\/\\]': "-"
#   '[<>:"\?\*\|]': _
#   '[?.":\!`]': ""
#   '[\\/]': _
#   '[\x00-\x1f]': _
#   '\.$': _
#   '\s+$': ""
#   "^-": _
#   '^\.': _
#   '^\s+': ""
#   "✝": "+"
ui:
  color: yes
musicbrainz:
  genres: yes
match:
  preferred:
    media: ["CD", "Digital Media"]
    countries: ["FR", "US", "GB", "UK"]
  distance_wights:
    media: 4.0
  ignored_media:
    - ".*Vinyl.*"
paths:
  default: Albums/%lower{%left{$albumartist, 1}}/$albumartist - $album%aunique{}/$track $title
  comp: Albums/_/$album%aunique{}/$track $title
  singleton: Singletons/%the{$artist} - $title
lastgenre:
  count: 2
fetchart:
  auto: no
  enforce_ratio: true
  minwidth: 1200
  maxwidth: 1200
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
replaygain:
  backend: metaflac
zero:
  fields:
    - comments
