[language-server.uwu_colors]
command = "uwu_colors"

[language-server.expert]
command = "expert"
args = ["--stdio"]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
# "https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "ansible/**.{yml,yaml}"
"kubernetes" = "k8s/**"

[[language]]
name = "css"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "css"] }
auto-format = true

[[language]]
name = "elixir"
language-servers = ["expert"]
auto-format = true
formatter = { command = "mix", args = ["format", "-"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "html"] }

[[language]]
name = "just"
auto-format = true
formatter = { command = "just", args = ["--justfile", "/dev/stdin", "--dump"] }

[[language]]
name = "toml"
auto-format = true
# language-servers = ["tombi", "uwu_colors"]

[[language]]
name = "svelte"
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-svelte",
  "--parser",
  "svelte"
] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.js"
] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.ts"
] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.jsx"
] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.tsx"
] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
auto-format = true
